# Generated by Django 5.2.15 on 2026-06-20 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('sender', models.EmailField(max_length=512)),
                ('subject', models.TextField(blank=True)),
                ('body_snippet', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
                'unique_together': {('user', 'gmail_message_id')},
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('auto_acknowledgement', 'Auto Acknowledgement'), ('rejection', 'Rejection'), ('interview_invite', 'Interview Invite'), ('follow_up_required', 'Follow Up Required'), ('recruiter_outreach', 'Recruiter Outreach'), ('offer', 'Offer')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('raw_openai_response', models.JSONField()),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='emails.email')),
            ],
        ),
    ]
