# Generated by Django 5.2.15 on 2026-06-20 17:45

import utils.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='google_access_token',
            field=utils.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='google_refresh_token',
            field=utils.fields.EncryptedTextField(blank=True),
        ),
    ]
