# Generated by Django 5.2.15 on 2026-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_history_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
